# Activate with: SPRING_PROFILES_ACTIVE=prod
spring.datasource.url=${BLOG_DATABASE_URL}
spring.datasource.username=${BLOG_DATABASE_USERNAME}
spring.datasource.password=${BLOG_DATABASE_PASSWORD}

spring.jpa.hibernate.ddl-auto=validate
spring.h2.console.enabled=false
