# Activate with: SPRING_PROFILES_ACTIVE=prod
spring.datasource.url=${BLOG_DATABASE_URL}
spring.datasource.username=${BLOG_DATABASE_USERNAME}
spring.datasource.password=${BLOG_DATABASE_PASSWORD}

spring.freemarker.expose-request-attributes=true
spring.jpa.hibernate.ddl-auto=validate
spring.h2.console.enabled=false

blog.registration.enabled=${BLOG_REGISTRATION_ENABLED}

blog.registration.mail.host=${BLOG_MAIL_HOST}
blog.registration.mail.port=${BLOG_MAIL_PORT}
blog.registration.mail.username=${BLOG_MAIL_USERNAME}
blog.registration.mail.password=${BLOG_MAIL_API_KEY}

blog.registration.mail.approver=${BLOG_APPROVER_EMAIL}
blog.registration.mail.sender=${BLOG_MAIL_FROM}
blog.registration.url=${BLOG_BASE_URL}
blog.registration.jwt=${BLOG_JWT_SECRET}
