# Activate with: SPRING_PROFILES_ACTIVE=prod
spring.datasource.url=${BLOG_DATABASE_URL}
spring.datasource.username=${BLOG_DATABASE_USERNAME}
spring.datasource.password=${BLOG_DATABASE_PASSWORD}

spring.freemarker.expose-request-attributes=true
spring.jpa.hibernate.ddl-auto=validate
spring.h2.console.enabled=false

blog.admin.username=${BLOG_ADMIN_USERNAME}
blog.admin.password-hash=${BLOG_ADMIN_PASSWORD_HASH}
